# Generated by Django 6.1.1 on 2026-09-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blood_type', models.CharField(max_length=3)),
                ('genotype', models.CharField(max_length=2)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('last_donation', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
