# Generated by Django 6.1.1 on 2026-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
